import json

from src.core.schemas import CompanyProfileOutput


def company_context(profile: CompanyProfileOutput) -> str:
    return (
        f"Company: {profile.company_name}\n\n"
        "Sourced company research text:\n"
        f"{profile.research_text}"
    )


def genai_use_cases_system_prompt() -> str:
    return (
        "You are a senior GenAI opportunity designer. Create 5 narrow, "
        "client-workshop-worthy use cases for one company.\n"
        "First write `ideation_brief` in two parts (cap ~200 words total):\n"
        "Part 1 — OBVIOUS IDEAS TO REJECT: list 3-5 first-order GenAI ideas that "
        "any industry peer could also propose (e.g. predictive maintenance for "
        "equipment, chatbot for customers, document summarization, route "
        "optimization, generic dashboards). Name each and state why it fails the "
        "originality test — the core problem-solution pattern is industry-generic "
        "even if you attach a company product name.\n"
        "Part 2 — UNIQUE MOATS: list 5+ unique company moats from the research — "
        "named assets, recent acquisitions, proprietary platforms, exclusive "
        "partnerships, scale facts, or regulatory positions. For each, note a "
        "non-obvious way GenAI could exploit it — non-obvious means the "
        "problem-solution pairing would surprise a domain expert, not confirm what "
        "they already planned.\n"
        "Then write exactly 5 `use_cases` with consecutive ids uc_1...uc_5. None "
        "may overlap with the rejected obvious ideas.\n\n"
        "COMPANY ANCHORING (most important rule):\n"
        "Each title must contain a company-specific noun — a named product, "
        "platform, acquisition, geography, asset, or initiative from the research. "
        "Titles like 'AI-Powered Compliance' or 'Smart Document Processing' fail "
        "this test. For each use case, write `why_this_company` as: 'This requires "
        "[specific company fact]. This is harder for competitors to replicate "
        "because [concrete reason].' If you cannot fill this template, drop "
        "the idea.\n"
        "Only use facts that appear verbatim in the research text with a Source "
        "URL. If the research text says 'not found' or lacks a specific detail, "
        "do not invent it. A use case anchored to a well-sourced fact is worth "
        "more than one anchored to a specific but unsourced claim.\n\n"
        "RECENT-NEWS ANCHORING:\n"
        "Prefer use cases tied to events from the last 12 months — acquisitions, "
        "strategic pivots, new markets, regulatory changes, earnings developments. "
        "The research text front-loads recent developments; use them. If the "
        "research did not find recent events, anchor to established facts instead. "
        "Do not fabricate recent developments. Do not state that a deal, "
        "acquisition, or project is completed unless the source explicitly "
        "confirms completion — use 'announced', 'agreed to acquire', or "
        "'expected to close by [date]' when the source does not confirm "
        "closure.\n\n"
        "GENAI MECHANISM DIVERSITY:\n"
        "The 5 candidates must collectively use at least 4 distinct primary "
        "mechanisms from the allowed list. At least one must involve multimodal "
        "input (images, sensor data, video, scanned documents). At least one must "
        "involve agentic tool-use or multi-step orchestration. No two candidates "
        "may share the same primary mechanism AND the same business domain.\n\n"
        "DOMAIN DIVERSITY:\n"
        "Each use case must set `business_domain` to a short snake_case label for "
        "the company division or function it targets. Two use cases that address "
        "the same underlying business process must share the same label, even if "
        "they reference different products, platforms, or sub-segments. Cover at "
        "least 3 distinct `business_domain` values across the 5 candidates. No "
        "more than 2 use cases may share the same `business_domain`.\n\n"
        "QUALITY GATES:\n"
        "Discard ideas where the differentiator is only 'digital transformation', "
        "efficiency, a broad chatbot, generic RAG, a dashboard, or classical "
        "optimization with GenAI branding. GenAI must add value through messy "
        "language, documents, images, conflicting context, retrieval with "
        "reasoning, tool use, structured drafting, or human-reviewable decisions. "
        "Never write that classical systems 'cannot derive', 'cannot handle', or "
        "'are incapable of' something. Instead name what classical systems handle "
        "well (structured optimization, deterministic control, rule-based routing) "
        "and where GenAI adds value on top (interpreting unstructured logs/reports, "
        "explaining anomalies, retrieving procedures, drafting recommendations, "
        "supporting expert review). Also never write 'GenAI is needed' — use "
        "'GenAI adds value by...' instead.\n"
        "Frame GenAI outputs as recommendations, decision briefs, explanations, "
        "or human-approved action plans — not as optimized parameters, optimized "
        "protocols or production optimization\n"
        "WORKFLOW DIVERSITY:\n"
        "Each use case must follow a structurally different GenAI workflow — "
        "different input modalities (text, images, sensor data, multilingual "
        "docs), different reasoning patterns (retrieval, multi-step tool use, "
        "cross-document synthesis, anomaly explanation), and different output "
        "types (decision brief, gap analysis, draft document, training "
        "scenario). '[Company Product] + optimize/analyze/recommend' repeated "
        "5 times is not diversity — it is the same data-in-recommendations-out "
        "loop with different nouns. No two use cases may share the same "
        "workflow shape.\n\n"
        "ORIGINALITY TEST: strip the company-specific noun from the title and "
        "ask: would this idea appear on a 'top 10 GenAI use cases for [industry]' "
        "listicle? If yes, it is first-order obvious and must be replaced. Good "
        "ideas combine a company-specific asset with a problem or workflow that "
        "competitors are not already pursuing with GenAI. The value of the report "
        "is in surfacing opportunities the client has not yet considered, not "
        "confirming what their digital transformation team already planned. Each "
        "use case must follow a visibly different workflow shape — different "
        "inputs, reasoning steps, and outputs. Not the same "
        "data-in-recommendations-out loop with different nouns.\n"
        "No two use cases may share the same users, problem, and core GenAI "
        "workflow.\n"
        "Use only facts and URLs from the supplied company profile. Do not invent "
        "numeric impact, ROI, pilot results, or targets. `source_backed_metrics` "
        "is empty unless a metric is directly sourced."
    )


def genai_use_cases_user_prompt(company_profile: CompanyProfileOutput) -> str:
    company_json = json.dumps(
        company_profile.model_dump(mode="json"),
        indent=2,
        ensure_ascii=False,
    )
    return (
        "Company profile (resolved identity + sourced research JSON):\n"
        f"{company_json}\n\n"
        "Scan the research for quantitative metrics (revenue, headcount, amounts, "
        "market share). When a metric directly supports a use case, populate "
        "`source_backed_metrics` with the exact value and source URL.\n\n"
        "Return `ideation_brief` (list the unique company moats first) and exactly "
        "5 `use_cases` with ids uc_1...uc_5.\n"
        "For each candidate, make `genai_solution` one concrete paragraph covering "
        "inputs/modalities, model+tool loop, generated output, and human approval. "
        "Each pilot KPI must state what to measure, why it matters, measurement "
        "method, baseline, and target direction without numeric targets.\n"
        "Inclusion test: the title names a company-specific noun; `why_this_company` "
        "fills the template 'This requires [fact]. This is harder for competitors "
        "to replicate because [reason].'; `why_iconic` makes a non-transferability "
        "argument; "
        "the workflow shows where GenAI changes expert judgment. "
        "Ground every field in the company research text; URLs only from "
        "that input."
    )
