from datetime import date


def web_search_system_prompt(today: date) -> str:
    return (
        "You are a research assistant. Use web search to find accurate, "
        "up-to-date information. Cite the source URL for every fact you report. "
        "Be concise and to the point. "
        f"The current date is {today:%Y-%m-%d}; use it in searches when recency "
        "matters.\n"
        "ANTI-HALLUCINATION RULES:\n"
        "Every fact you report must come from the search results you received. "
        "Do not supplement with prior knowledge, training data, or common "
        "assumptions.\n"
        "Every URL you cite must be a URL returned by the search tool. Never "
        "construct a URL from a domain name and a guessed path.\n"
        "Every claim must be supported by a source URL, which needs to be next "
        "to the claim, do not add a url list at the end.\n"
        "If a search does not return the information you expected, report that "
        "the information was not found. Do not guess numbers, dates, names, or "
        "amounts.\n"
        "Complete your entire task in one pass. Never ask for confirmation, "
        "permission, or whether you should continue. Execute all requested "
        "steps without stopping."
    )


def research_prompt(company_query: str) -> str:
    return (
        f"Resolve and research this company: {company_query}\n\n"
        "First establish the company identity: find the official company name, "
        "website, headquarters country, primary industry, and note any ambiguity "
        "(similarly named companies, subsidiaries, brands). Use Wikipedia or the "
        "official website. Then immediately proceed to deep research without "
        "stopping — search for the context needed for a GenAI recommendation "
        "workflow. Search for recent developments (last 12 months) first: "
        "acquisitions, earnings results, strategic pivots, new market entries, "
        "major contracts, regulatory changes, and leadership moves. Then cover: "
        "business lines; key customers and segments; named products, platforms, "
        "or proprietary technologies; strategic priorities and initiatives; "
        "geography and markets; operational pain points; regulatory and customer "
        "pressure; growth opportunities; technology and digital transformation "
        "context.\n"
        "Format every finding as: Claim: one concise factual claim; "
        "Source URL: one full http(s) URL. Omit claims without a URL. "
        "Claim and Source URL must be next to each other.\n"
        "Do not invent facts when sources are missing.\n"
        "Prefer sources in this order: official company website; annual report / "
        "universal registration document; investor presentation; official press "
        "release; reputable business or industry publication; Wikipedia only as "
        "fallback for basic identity.\n"
        "Aim for breadth: cover multiple business lines and recent events rather "
        "than deep-diving one area. Do not cite blogs or weak sources when "
        "official sources exist.\n"
        "CRITICAL: only report facts found in search results. If a search does "
        "not return recent acquisitions, revenue, or leadership changes, do not "
        "guess — write 'Not found in search results' for topics with no results. "
        "Never construct a URL; every Source URL must be copied verbatim from a "
        "search result."
    )
